# This is the Docker compose file for the project

# First the nginx service
services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mariadb

# then the DB
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PSW}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PSW}
    ports:
      - "3306:3306"
    volumes:
      - /home/mburakow/data/mariadb_data:/var/lib/mysql

# then wordpress
  wordpress:
    build: ./wordpress/.
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PSW}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
    ports:
      - "8080:80"
    volumes:
      - /home/mburakow/data/wordpress_data:/var/www/html


