# This is the Docker compose file for the project

# First the nginx service
services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"

